name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Create Windows EXE
        run: npm run dist

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/*.exe
